# Generated by Django 2.2.4 on 2019-08-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190813_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_date',
        ),
    ]
