# Generated by Django 2.2.4 on 2019-08-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_comment_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='news.Category'),
            preserve_default=False,
        ),
    ]
